@echo off
echo Killing any existing Python bot processes...
taskkill /F /IM python.exe /T 2>nul
taskkill /F /IM pythonw.exe /T 2>nul
echo Done. Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting bot...
call "START BOT.bat"
